---
- name: gnome-dconf role
  tags:
    - gnome-dconf
  block:

  # normal user
  - when: gnome_dconf_user != "global"
    become: true
    become_user: "{{ gnome_dconf_user }}"
    ansible.builtin.import_tasks: "{{ role_path }}/tasks/{{ gnome_dconf_subtask }}"